version: "3"
services:
  nextcloud:
    image: nextcloud
    ports:
      - "9500:80"
    volumes:
      - ./data:/var/www/html
      # - "./hosts:/etc/hosts"
      # - "./db:/etc/x-ui"
      # - "./cert:/root/cert"
    # networks:
      # xuipv6:
        # enable_ipv6: true
        # driver: bridge
        # com.dockere.network.enable_ipv6: true
