version: "3"
services:
  x-ui-services:
    image: enwaiax/x-ui
    ports:
      - "9100-9199:9100-9199"
    volumes:
      # - "./hosts:/etc/hosts"
      - "./db:/etc/x-ui"
      - "./cert:/root/cert"
    # networks:
      # xuipv6:
        # enable_ipv6: true
        # driver: bridge
        # com.dockere.network.enable_ipv6: true
